### ISSUE TITLE
Fail validate openAPI spec

### ISSUE THREAD

**Issue by illiyyin** [valida-team/valida#40]
I'm using gin-swagger to generate open api spec and generate swagger page
![image](https://github.com/user-attachments/assets/bbd1bb24-eb51-4983-aace-7ed7b81b12ce)

but when I tried to run `valida test -f docs/swagger.json` I got this error
![image](https://github.com/user-attachments/assets/86b6ed53-4341-4c29-b97b-81c04d27b9c2)

**Comment by elangbayu** [comment]
I am sorry but currently we're only supporting openapi file v3, not swagger
